import type { Metadata } from "next";
import { Frijole, Sniglet } from "next/font/google";
import { ThemeProvider } from "./_components/theme-provider";
import "./globals.css";

// Sniglet supports multiple weights
const sniglet = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"],
  variable: "--font-sniglet",
});

// Frijole only supports 400 weight
const frijole = Frijole({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-frijole",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${frijole.variable} ${sniglet.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
